services:
  mongodb:
    image: mongo:7.0
    container_name: custodia-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: custodia_dev

  mongo-express:
    image: mongo-express:1.0
    container_name: custodia-mongo-ui
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data_dev:
